import type { SampleContract } from "./index";

export const nda: SampleContract = {
  id: "nda",
  title: "One-Way Non-Disclosure Agreement — Halloran Data Systems, Inc.",
  cardTitle: "The NDA",
  blurb: "Two parties, one secret, a three-year tail.",
  text: `NON-DISCLOSURE AGREEMENT

This One-Way Non-Disclosure Agreement ("Agreement") is entered into as of April 14, 2026, by and between Halloran Data Systems, Inc., a Delaware corporation with offices at 1200 Foundry Street, Floor 6, Austin, Texas 78702 ("Company"), and Priya N. Raghavan, an individual residing in Austin, Texas ("Employee"). The Employee is signing this Agreement as a condition of employment with the Company. There are no other parties to this Agreement.

WHEREAS the Company develops and operates data infrastructure software and possesses information relating to its products, customers, finances, and internal operations; and

WHEREAS the Employee will, in the course of employment, come into contact with information belonging to the Company and will generate information in connection with that employment; and

WHEREAS the Company requires the Employee's unconditional undertaking with respect to all such information; NOW, THEREFORE, in consideration of employment and the promises below, the parties agree as follows:

1. Purpose. The purpose of this Agreement is to protect the Company's information assets. The Employee acknowledges that the Company would suffer irreparable harm if the Employee were to disclose or use the Company's information outside the scope of employment, and that this Agreement is intended to prevent any such disclosure or use.

2. Confidential Information. "Confidential Information" means any and all information, in any form or medium, that is disclosed to, generated by, or observed by the Employee in connection with the Employee's employment, including information relating to the Company's products, source code, customers, pricing, finances, personnel, and business plans. For the avoidance of doubt, information is Confidential Information under this Agreement whether or not it is marked as confidential, and whether or not it is or becomes generally known to the public or available from third-party sources. The parties intend that this definition be read as broadly as applicable law allows.

3. Obligations of the Employee. The Employee shall hold all Confidential Information in strict confidence, shall not disclose it to any person or entity other than authorized Company personnel, shall not use it except in the performance of duties for the benefit of the Company, and shall take every measure the Company reasonably requests to safeguard it. The Employee shall notify the Company immediately upon becoming aware of any unauthorized disclosure or use of Confidential Information.

4. Scope of Application. The obligations of this Agreement apply to all Confidential Information, regardless of when, where, or how the Employee acquired it, including information acquired at Company events, in public settings, through conversations overheard at the office, or from remarks made by customers or other third parties. The Employee agrees that no knowledge, memory, or skill retained after employment ends is free of these obligations, and that nothing in this Agreement grants the Employee any residual right to use generalized knowledge, know-how, or impressions gained during employment.

5. Term and Survival. This Agreement begins on the Effective Date. The Employee's obligations under this Agreement apply during employment and survive the termination of employment indefinitely, without limitation as to duration, and are not excused by the passage of time, the end of the employment relationship, or the dissolution or reorganization of the Company.

6. No Obligations of the Company. This Agreement is one-way. The Company assumes no confidentiality obligation of any kind with respect to information the Employee provides to the Company, including information the Employee describes as personal or private, and nothing in this Agreement imposes any obligation on the Company. No license or right of any kind is granted to the Employee, by implication or otherwise, under this Agreement.

7. Indemnification and Remedies. The Employee shall indemnify and hold harmless the Company against any loss, cost, or expense arising out of any disclosure or use of Confidential Information by the Employee, whether intentional, negligent, or accidental. The parties agree that money damages would be inadequate and that the Company is entitled to injunctive relief without the necessity of posting a bond, in addition to all other remedies available at law or in equity.

8. Return of Materials; General Provisions. The Employee shall return all Confidential Information in the Employee's possession upon request and in any event upon termination of employment. This Agreement is governed by the laws of the State of Texas. It is the entire agreement of the parties regarding its subject matter, supersedes all prior discussions, and may be amended only in a writing signed by the Company. There are no third-party beneficiaries to this Agreement. The Employee confirms that the Employee has read this Agreement carefully and signed it voluntarily.

Agreed and accepted:

Halloran Data Systems, Inc. - By: Marcus T. Ellery, Chief People Officer - Date: April 14, 2026

Employee - Priya N. Raghavan - Date: April 14, 2026`,
};
